CREATE DATABASE IF NOT EXISTS `JSONRPCTEMPLATE`;
USE `JSONRPCTEMPLATE`;

SET @@global.time_zone = '+00:00';

DROP TABLE IF EXISTS `Event`;
DROP TABLE IF EXISTS `Authentication`;
DROP TABLE IF EXISTS `Account`;

CREATE TABLE `Account` (
	`AccountID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Username` VARCHAR(255) NOT NULL,
	`PasswordHash` VARCHAR(255) NOT NULL,
	`CreatedAtDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`UpdatedAtDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (`AccountID`),
	UNIQUE KEY `UX_Account_Username` (`Username`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Authentication` (
	`AuthenticationID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`AccountID` INT UNSIGNED NOT NULL,
	`AccessToken` VARCHAR(1023) NOT NULL,
	`RefreshToken` VARCHAR(1023) NOT NULL,
	`ExpiresAtDate` TIMESTAMP NOT NULL,
	`IssuedAtDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`AuthenticationID`),
	FOREIGN KEY (`AccountID`) REFERENCES `Account`(`AccountID`),
	INDEX `IDX_Authentication_AccessToken` (`AccessToken`(255)),
	INDEX `IDX_Authentication_RefreshToken` (`RefreshToken`(255))
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `Event` (
	`EventID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(255) NOT NULL,
	`Context` TEXT NOT NULL,
	`Data` TEXT NOT NULL,
	`OccuredAtDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`EventID`),
	INDEX `IDX_Event_Name` (`Name`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

LOCK TABLES `Account` WRITE;
INSERT INTO `Account` (`AccountID`, `Username`, `PasswordHash`) VALUES (1, 'root', '$2y$10$vp4oqD4Fqvu.3cmDno720urNgZv9myNbj4WgTzHXxiDxykFJyc80m');
UNLOCK TABLES;
